# Schema for the configuration files of the Coworking Demonstration module.
coworking.settings:
  type: config_object
  label: 'Coworking Demonstration settings'
  mapping:
    example:
      type: string
      label: 'Example'
